version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: durable-streams-server
    main: ./cmd/caddy
    binary: durable-streams-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/caddyserver/caddy/v2.CustomVersion={{.Version}}

archives:
  - id: default
    name_template: "durable-streams-server_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - Caddyfile

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance Improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other Changes"
      order: 999

release:
  github:
    owner: durable-streams
    name: durable-streams
  name_template: "Caddy Server v{{.Version}}"
  prerelease: auto
  draft: false
