linkWorkspacePackages: true
preferWorkspacePackages: true

packages:
  - docs
  - packages/*
  - examples/*
  - examples/**/*

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - lmdb
