/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionRouteImport } from './routes/session'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionIndexRouteImport } from './routes/session/index'
import { Route as SessionIdRouteImport } from './routes/session/$id'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiSessionControlRouteImport } from './routes/api/session-control'
import { Route as ApiStreamIdRouteImport } from './routes/api/stream/$id'

const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIndexRoute = SessionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionRoute,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SessionRoute,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionControlRoute = ApiSessionControlRouteImport.update({
  id: '/api/session-control',
  path: '/api/session-control',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamIdRoute = ApiStreamIdRouteImport.update({
  id: '/api/stream/$id',
  path: '/api/stream/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/session': typeof SessionRouteWithChildren
  '/api/session-control': typeof ApiSessionControlRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/session/$id': typeof SessionIdRoute
  '/session/': typeof SessionIndexRoute
  '/api/stream/$id': typeof ApiStreamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/session-control': typeof ApiSessionControlRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/session/$id': typeof SessionIdRoute
  '/session': typeof SessionIndexRoute
  '/api/stream/$id': typeof ApiStreamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/session': typeof SessionRouteWithChildren
  '/api/session-control': typeof ApiSessionControlRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/session/$id': typeof SessionIdRoute
  '/session/': typeof SessionIndexRoute
  '/api/stream/$id': typeof ApiStreamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/session'
    | '/api/session-control'
    | '/api/sessions'
    | '/session/$id'
    | '/session/'
    | '/api/stream/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/session-control'
    | '/api/sessions'
    | '/session/$id'
    | '/session'
    | '/api/stream/$id'
  id:
    | '__root__'
    | '/'
    | '/session'
    | '/api/session-control'
    | '/api/sessions'
    | '/session/$id'
    | '/session/'
    | '/api/stream/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionRoute: typeof SessionRouteWithChildren
  ApiSessionControlRoute: typeof ApiSessionControlRoute
  ApiSessionsRoute: typeof ApiSessionsRoute
  ApiStreamIdRoute: typeof ApiStreamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/': {
      id: '/session/'
      path: '/'
      fullPath: '/session/'
      preLoaderRoute: typeof SessionIndexRouteImport
      parentRoute: typeof SessionRoute
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof SessionRoute
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session-control': {
      id: '/api/session-control'
      path: '/api/session-control'
      fullPath: '/api/session-control'
      preLoaderRoute: typeof ApiSessionControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/$id': {
      id: '/api/stream/$id'
      path: '/api/stream/$id'
      fullPath: '/api/stream/$id'
      preLoaderRoute: typeof ApiStreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SessionRouteChildren {
  SessionIdRoute: typeof SessionIdRoute
  SessionIndexRoute: typeof SessionIndexRoute
}

const SessionRouteChildren: SessionRouteChildren = {
  SessionIdRoute: SessionIdRoute,
  SessionIndexRoute: SessionIndexRoute,
}

const SessionRouteWithChildren =
  SessionRoute._addFileChildren(SessionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionRoute: SessionRouteWithChildren,
  ApiSessionControlRoute: ApiSessionControlRoute,
  ApiSessionsRoute: ApiSessionsRoute,
  ApiStreamIdRoute: ApiStreamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
