/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiSudokuCellsRouteImport } from './routes/api/sudoku-cells'
import { Route as ApiPlayerStatsRouteImport } from './routes/api/player-stats'
import { Route as ApiGameStateRouteImport } from './routes/api/game-state'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSudokuCellsRoute = ApiSudokuCellsRouteImport.update({
  id: '/api/sudoku-cells',
  path: '/api/sudoku-cells',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayerStatsRoute = ApiPlayerStatsRouteImport.update({
  id: '/api/player-stats',
  path: '/api/player-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameStateRoute = ApiGameStateRouteImport.update({
  id: '/api/game-state',
  path: '/api/game-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/game-state': typeof ApiGameStateRoute
  '/api/player-stats': typeof ApiPlayerStatsRoute
  '/api/sudoku-cells': typeof ApiSudokuCellsRoute
  '/api/users': typeof ApiUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/game-state': typeof ApiGameStateRoute
  '/api/player-stats': typeof ApiPlayerStatsRoute
  '/api/sudoku-cells': typeof ApiSudokuCellsRoute
  '/api/users': typeof ApiUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/game-state': typeof ApiGameStateRoute
  '/api/player-stats': typeof ApiPlayerStatsRoute
  '/api/sudoku-cells': typeof ApiSudokuCellsRoute
  '/api/users': typeof ApiUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/game-state'
    | '/api/player-stats'
    | '/api/sudoku-cells'
    | '/api/users'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/game-state'
    | '/api/player-stats'
    | '/api/sudoku-cells'
    | '/api/users'
    | '/api/auth/$'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/game-state'
    | '/api/player-stats'
    | '/api/sudoku-cells'
    | '/api/users'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiGameStateRoute: typeof ApiGameStateRoute
  ApiPlayerStatsRoute: typeof ApiPlayerStatsRoute
  ApiSudokuCellsRoute: typeof ApiSudokuCellsRoute
  ApiUsersRoute: typeof ApiUsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sudoku-cells': {
      id: '/api/sudoku-cells'
      path: '/api/sudoku-cells'
      fullPath: '/api/sudoku-cells'
      preLoaderRoute: typeof ApiSudokuCellsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/player-stats': {
      id: '/api/player-stats'
      path: '/api/player-stats'
      fullPath: '/api/player-stats'
      preLoaderRoute: typeof ApiPlayerStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game-state': {
      id: '/api/game-state'
      path: '/api/game-state'
      fullPath: '/api/game-state'
      preLoaderRoute: typeof ApiGameStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiGameStateRoute: ApiGameStateRoute,
  ApiPlayerStatsRoute: ApiPlayerStatsRoute,
  ApiSudokuCellsRoute: ApiSudokuCellsRoute,
  ApiUsersRoute: ApiUsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
