/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiServerInfoRouteImport } from './routes/api/server-info'
import { Route as ApiWebhookAgentsRouteImport } from './routes/api/webhook.agents'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServerInfoRoute = ApiServerInfoRouteImport.update({
  id: '/api/server-info',
  path: '/api/server-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookAgentsRoute = ApiWebhookAgentsRouteImport.update({
  id: '/api/webhook/agents',
  path: '/api/webhook/agents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/server-info': typeof ApiServerInfoRoute
  '/api/webhook/agents': typeof ApiWebhookAgentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/server-info': typeof ApiServerInfoRoute
  '/api/webhook/agents': typeof ApiWebhookAgentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/server-info': typeof ApiServerInfoRoute
  '/api/webhook/agents': typeof ApiWebhookAgentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/server-info' | '/api/webhook/agents'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/server-info' | '/api/webhook/agents'
  id: '__root__' | '/' | '/api/server-info' | '/api/webhook/agents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiServerInfoRoute: typeof ApiServerInfoRoute
  ApiWebhookAgentsRoute: typeof ApiWebhookAgentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/server-info': {
      id: '/api/server-info'
      path: '/api/server-info'
      fullPath: '/api/server-info'
      preLoaderRoute: typeof ApiServerInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/agents': {
      id: '/api/webhook/agents'
      path: '/api/webhook/agents'
      fullPath: '/api/webhook/agents'
      preLoaderRoute: typeof ApiWebhookAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiServerInfoRoute: ApiServerInfoRoute,
  ApiWebhookAgentsRoute: ApiWebhookAgentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
