// Generated by wrangler types command
// Run: pnpm cf-typegen

// Extend the Cloudflare.Env interface with our bindings
declare namespace Cloudflare {
  interface Env {
    DURABLE_STREAMS_URL: string
    DURABLE_STREAMS_AUTH?: string // Auth token for Electric Cloud
    TEAM_COOKIE_SECRET: string
    GAME_WRITER: DurableObjectNamespace
    NODE_ENV?: string
  }
}

// Add the env export to cloudflare:workers module
// (provided at runtime by @cloudflare/vite-plugin)
declare module "cloudflare:workers" {
  const env: Cloudflare.Env
}
