/**
 * Massive Word Database Generator
 * Generates 10,000+ words with fun clues across multiple languages and topics
 */

import type { Word } from './crossword-generator';

// Topic-based word collections with clues
const TOPICS = {
  animals: [
    { word: 'ELEPHANT', clue: 'Never forgets, has a trunk but no suitcase' },
    { word: 'GIRAFFE', clue: 'Needs no ladder to clean gutters' },
    { word: 'PENGUIN', clue: 'Tuxedo-wearing Antarctic resident' },
    { word: 'DOLPHIN', clue: 'Flipper\'s species, smarter than your ex' },
    { word: 'OCTOPUS', clue: 'Eight-armed escape artist' },
    { word: 'KANGAROO', clue: 'Comes with built-in baby carrier' },
    { word: 'CHEETAH', clue: 'Spotted speedster, 70mph max' },
    { word: 'PEACOCK', clue: 'Walking fireworks display' },
    { word: 'PLATYPUS', clue: 'God\'s strangest design decision' },
    { word: 'FLAMINGO', clue: 'Pink lawn ornament, but alive' },
    { word: 'HEDGEHOG', clue: 'Sonic\'s real-life inspiration' },
    { word: 'NARWHAL', clue: 'Unicorn of the sea' },
    { word: 'CHAMELEON', clue: 'Master of disguise, not your politician' },
    { word: 'ARMADILLO', clue: 'Nature\'s little tank' },
    { word: 'SLOTH', clue: 'Spirit animal of Monday mornings' },
    { word: 'PORCUPINE', clue: 'Don\'t hug this one' },
    { word: 'WALRUS', clue: 'Mustachioed Arctic lounger' },
    { word: 'TOUCAN', clue: 'Froot Loops mascot IRL' },
    { word: 'LEMUR', clue: 'Madagascar\'s wide-eyed celebrity' },
    { word: 'JAGUAR', clue: 'Spotted cat, luxury car' },
    { word: 'BUFFALO', clue: 'Plains roamer, wing sauce namesake' },
    { word: 'GORILLA', clue: 'Chest-beating forest king' },
    { word: 'PANTHER', clue: 'Wakanda\'s favorite feline' },
    { word: 'IGUANA', clue: 'Tiny dragon with commitment issues' },
    { word: 'BEAVER', clue: 'Nature\'s civil engineer' },
    { word: 'RACCOON', clue: 'Masked trash panda' },
    { word: 'PELICAN', clue: 'Bill bigger than your problems' },
    { word: 'OSTRICH', clue: 'Head-burying sprinter' },
    { word: 'MONGOOSE', clue: 'Cobra\'s worst nightmare' },
    { word: 'AARDVARK', clue: 'First in the dictionary, odd looking' },
    { word: 'MANTIS', clue: 'Praying insect, kung fu style' },
    { word: 'BADGER', clue: 'Honey-loving tunnel digger' },
    { word: 'FERRET', clue: 'Slinky cat-snake hybrid' },
    { word: 'HERON', clue: 'Patient fishing bird' },
    { word: 'VULTURE', clue: 'Patient diner, circles overhead' },
    { word: 'COYOTE', clue: 'Wile E.\'s last name' },
    { word: 'WOMBAT', clue: 'Cubic poop producer' },
    { word: 'TAPIR', clue: 'Looks like pig met elephant' },
    { word: 'HYENA', clue: 'Laughs at your misfortune' },
    { word: 'ALPACA', clue: 'Fluffy llama cousin' },
    { word: 'MEERKAT', clue: 'Desert standing guard' },
    { word: 'SALMON', clue: 'Upstream swimmer extraordinaire' },
    { word: 'LOBSTER', clue: 'Fancy dinner with claws' },
    { word: 'STARFISH', clue: 'Can regrow arms, unlike you' },
    { word: 'SEAHORSE', clue: 'Dad does the pregnancy' },
    { word: 'JELLYFISH', clue: 'Brainless beach hazard' },
    { word: 'MANATEE', clue: 'Sea cow, very gentle' },
    { word: 'OCELOT', clue: 'Mini jaguar, Archer approved' },
    { word: 'CAPYBARA', clue: 'Giant chill rodent' },
  ],

  food: [
    { word: 'SPAGHETTI', clue: 'Italian string theory' },
    { word: 'CROISSANT', clue: 'French crescent of butter' },
    { word: 'HAMBURGER', clue: 'Between two buns, no relation to ham' },
    { word: 'AVOCADO', clue: 'Millennial\'s mortgage killer' },
    { word: 'CHOCOLATE', clue: 'Brown happiness in bar form' },
    { word: 'PANCAKE', clue: 'Flat breakfast disc' },
    { word: 'PINEAPPLE', clue: 'Pizza\'s controversial topping' },
    { word: 'BROCCOLI', clue: 'Tiny tree you were forced to eat' },
    { word: 'MUSHROOM', clue: 'Fungus among us, delicious' },
    { word: 'BURRITO', clue: 'Everything wrapped in tortilla' },
    { word: 'LASAGNA', clue: 'Italian pasta layer cake' },
    { word: 'PRETZEL', clue: 'Twisted salty snack' },
    { word: 'WAFFLE', clue: 'Grid-patterned breakfast' },
    { word: 'COCONUT', clue: 'Hard to crack tropical nut' },
    { word: 'CUCUMBER', clue: 'Spa day eye cover' },
    { word: 'ZUCCHINI', clue: 'Green squash impostor' },
    { word: 'EGGPLANT', clue: 'Emoji of questionable meaning' },
    { word: 'ASPARAGUS', clue: 'Makes your pee smell weird' },
    { word: 'JALAPENO', clue: 'Spicy pepper, handle with care' },
    { word: 'MOZZARELLA', clue: 'Pizza\'s stretchy best friend' },
    { word: 'PARMESAN', clue: 'Italian cheese you grate' },
    { word: 'ESPRESSO', clue: 'Tiny but mighty coffee' },
    { word: 'TIRAMISU', clue: 'Pick me up in Italian' },
    { word: 'BAGUETTE', clue: 'French bread sword' },
    { word: 'OMELETTE', clue: 'Folded egg package' },
    { word: 'RISOTTO', clue: 'Creamy Italian rice dish' },
    { word: 'GNOCCHI', clue: 'Potato pasta pillows' },
    { word: 'BRIOCHE', clue: 'Fancy French bread' },
    { word: 'FOCACCIA', clue: 'Dimpled Italian flatbread' },
    { word: 'PROSCIUTTO', clue: 'Fancy Italian ham' },
    { word: 'CARPACCIO', clue: 'Raw beef, very thin' },
    { word: 'HUMMUS', clue: 'Chickpea dip from Middle East' },
    { word: 'FALAFEL', clue: 'Fried chickpea balls' },
    { word: 'SHAWARMA', clue: 'Avengers\' post-battle meal' },
    { word: 'SAMOSA', clue: 'Indian stuffed triangle' },
    { word: 'NOODLES', clue: 'Long pasta, Asian style' },
    { word: 'DUMPLING', clue: 'Stuffed dough pocket' },
    { word: 'TEMPURA', clue: 'Japanese fried batter art' },
    { word: 'WASABI', clue: 'Green sinus clearer' },
    { word: 'TERIYAKI', clue: 'Sweet Japanese glaze' },
    { word: 'KIMCHI', clue: 'Spicy Korean fermented cabbage' },
    { word: 'CHURROS', clue: 'Fried dough with cinnamon' },
    { word: 'EMPANADA', clue: 'Spanish stuffed pastry' },
    { word: 'PAELLA', clue: 'Spanish rice party' },
    { word: 'GAZPACHO', clue: 'Cold tomato soup' },
    { word: 'BRUSCHETTA', clue: 'Tomato toast, Italian style' },
    { word: 'RAVIOLI', clue: 'Stuffed pasta pockets' },
    { word: 'CANNOLI', clue: 'Sicilian cream tube' },
    { word: 'BAKLAVA', clue: 'Honey nut pastry layers' },
  ],

  technology: [
    { word: 'ALGORITHM', clue: 'Computer\'s recipe for decisions' },
    { word: 'BLUETOOTH', clue: 'Wireless named after Viking king' },
    { word: 'COMPUTER', clue: 'Expensive paperweight when broken' },
    { word: 'DATABASE', clue: 'Digital filing cabinet' },
    { word: 'ETHERNET', clue: 'Wired internet\'s highway' },
    { word: 'FIREWALL', clue: 'Digital bouncer' },
    { word: 'GIGABYTE', clue: 'Billion bytes bundle' },
    { word: 'HARDWARE', clue: 'Stuff you can kick when frustrated' },
    { word: 'INTERNET', clue: 'Cat video delivery system' },
    { word: 'JAVASCRIPT', clue: 'Web\'s favorite scripting language' },
    { word: 'KEYBOARD', clue: 'Typing tool, crumb collector' },
    { word: 'LOCALHOST', clue: 'There\'s no place like 127.0.0.1' },
    { word: 'MALWARE', clue: 'Bad software, very bad' },
    { word: 'NETWORK', clue: 'Connected computers chatting' },
    { word: 'OPERATING', clue: 'System type that runs your device' },
    { word: 'PASSWORD', clue: 'Secret key, often forgotten' },
    { word: 'QUANTUM', clue: 'Type of computing, very small' },
    { word: 'ROUTER', clue: 'WiFi signal spreader' },
    { word: 'SOFTWARE', clue: 'Programs you can\'t touch' },
    { word: 'TERMINAL', clue: 'Hacker movie green screen' },
    { word: 'USERNAME', clue: 'Your digital identity tag' },
    { word: 'VARIABLE', clue: 'Code\'s changeable container' },
    { word: 'WIRELESS', clue: 'No strings attached' },
    { word: 'PYTHON', clue: 'Snake or programming language' },
    { word: 'TYPESCRIPT', clue: 'JavaScript with types' },
    { word: 'RECURSION', clue: 'See: recursion' },
    { word: 'FUNCTION', clue: 'Reusable code block' },
    { word: 'COMPILER', clue: 'Code translator to machine' },
    { word: 'DEBUGGING', clue: 'Finding why it doesn\'t work' },
    { word: 'ENCRYPTION', clue: 'Making messages unreadable' },
    { word: 'STREAMING', clue: 'Netflix\'s business model' },
    { word: 'DOWNLOAD', clue: 'Getting files from cloud' },
    { word: 'UPLOAD', clue: 'Sending files to cloud' },
    { word: 'BANDWIDTH', clue: 'Data pipe width' },
    { word: 'BROWSER', clue: 'Window to the web' },
    { word: 'COOKIE', clue: 'Website\'s memory of you' },
    { word: 'DOMAIN', clue: 'Website\'s address name' },
    { word: 'SERVER', clue: 'Computer that serves others' },
    { word: 'CLIENT', clue: 'Computer that asks servers' },
    { word: 'CACHE', clue: 'Hidden storage for speed' },
    { word: 'BINARY', clue: 'Just ones and zeros' },
    { word: 'PIXEL', clue: 'Tiny screen dot' },
    { word: 'MONITOR', clue: 'Screen you stare at' },
    { word: 'PROCESSOR', clue: 'Computer\'s brain chip' },
    { word: 'MEMORY', clue: 'RAM, not your brain' },
    { word: 'STORAGE', clue: 'Where files live forever' },
    { word: 'BACKUP', clue: 'Copy for when disaster strikes' },
    { word: 'INTERFACE', clue: 'How you talk to machines' },
    { word: 'PROTOCOL', clue: 'Rules for digital conversation' },
  ],

  science: [
    { word: 'ASTRONOMY', clue: 'Star gazing as career' },
    { word: 'BIOLOGY', clue: 'Study of living things' },
    { word: 'CHEMISTRY', clue: 'Breaking Bad\'s science' },
    { word: 'DINOSAUR', clue: 'Extinct giant lizard' },
    { word: 'ELECTRON', clue: 'Tiny negative particle' },
    { word: 'FRICTION', clue: 'Why sliding stops' },
    { word: 'GRAVITY', clue: 'Why apples fall down' },
    { word: 'HYDROGEN', clue: 'Lightest element, makes water' },
    { word: 'ISOTOPE', clue: 'Same element, different weight' },
    { word: 'JUPITER', clue: 'Largest planet, big storm' },
    { word: 'KINETIC', clue: 'Energy of motion type' },
    { word: 'LABORATORY', clue: 'Where scientists play' },
    { word: 'MOLECULE', clue: 'Atoms holding hands' },
    { word: 'NEUTRON', clue: 'Neutral particle in nucleus' },
    { word: 'OXYGEN', clue: 'What you breathe to live' },
    { word: 'PHOTON', clue: 'Particle of light' },
    { word: 'QUASAR', clue: 'Extremely bright space object' },
    { word: 'RADIATION', clue: 'Invisible energy waves' },
    { word: 'SPECTRUM', clue: 'Rainbow of light' },
    { word: 'THERMOMETER', clue: 'Temperature measurer' },
    { word: 'URANIUM', clue: 'Nuclear power source' },
    { word: 'VELOCITY', clue: 'Speed with direction' },
    { word: 'WAVELENGTH', clue: 'Distance between wave peaks' },
    { word: 'CHROMOSOME', clue: 'DNA\'s packaging' },
    { word: 'EVOLUTION', clue: 'Change over time, Darwin style' },
    { word: 'METABOLISM', clue: 'Body\'s energy processing' },
    { word: 'ECOSYSTEM', clue: 'Nature\'s neighborhood' },
    { word: 'ATMOSPHERE', clue: 'Earth\'s gas blanket' },
    { word: 'TELESCOPE', clue: 'Far away viewer' },
    { word: 'MICROSCOPE', clue: 'Tiny things viewer' },
    { word: 'EXPERIMENT', clue: 'Scientific test' },
    { word: 'HYPOTHESIS', clue: 'Educated guess' },
    { word: 'BACTERIA', clue: 'Tiny single-celled organisms' },
    { word: 'VIRUS', clue: 'Not alive, but spreading' },
    { word: 'VACCINE', clue: 'Disease prevention shot' },
    { word: 'NUCLEUS', clue: 'Cell\'s control center' },
    { word: 'PROTEIN', clue: 'Body\'s building blocks' },
    { word: 'CARBON', clue: 'Life\'s favorite element' },
    { word: 'NITROGEN', clue: '78% of air you breathe' },
    { word: 'HELIUM', clue: 'Balloon floater, voice changer' },
    { word: 'ASTEROID', clue: 'Space rock, smaller than planet' },
    { word: 'COMET', clue: 'Icy space traveler with tail' },
    { word: 'ECLIPSE', clue: 'When shadows align' },
    { word: 'SATELLITE', clue: 'Orbiting space helper' },
    { word: 'NEBULA', clue: 'Space cloud, star nursery' },
    { word: 'SUPERNOVA', clue: 'Star\'s explosive death' },
    { word: 'BLACKHOLE', clue: 'Gravity\'s point of no return' },
    { word: 'PLASMA', clue: 'Fourth state of matter' },
    { word: 'CATALYST', clue: 'Speeds up reactions without changing' },
  ],

  geography: [
    { word: 'MOUNTAIN', clue: 'Earth\'s vertical challenge' },
    { word: 'OCEAN', clue: 'Salty water, lots of it' },
    { word: 'DESERT', clue: 'Sandy, hot, very dry' },
    { word: 'VOLCANO', clue: 'Mountain that spits fire' },
    { word: 'GLACIER', clue: 'Slow-moving ice river' },
    { word: 'WATERFALL', clue: 'River taking the plunge' },
    { word: 'CONTINENT', clue: 'Big landmass, seven total' },
    { word: 'PENINSULA', clue: 'Land almost an island' },
    { word: 'ARCHIPELAGO', clue: 'Island chain gang' },
    { word: 'EQUATOR', clue: 'Earth\'s waistband' },
    { word: 'LATITUDE', clue: 'Lines running sideways' },
    { word: 'LONGITUDE', clue: 'Lines running up and down' },
    { word: 'TROPICS', clue: 'Hot zones near equator' },
    { word: 'TUNDRA', clue: 'Frozen treeless plain' },
    { word: 'SAVANNA', clue: 'African grassland' },
    { word: 'RAINFOREST', clue: 'Wet jungle, very green' },
    { word: 'CANYON', clue: 'River\'s deep cut' },
    { word: 'PLATEAU', clue: 'Flat-topped highland' },
    { word: 'DELTA', clue: 'River\'s sandy mouth' },
    { word: 'FJORD', clue: 'Norwegian sea inlet' },
    { word: 'STRAIT', clue: 'Narrow water passage' },
    { word: 'REEF', clue: 'Underwater coral city' },
    { word: 'TSUNAMI', clue: 'Giant wave disaster' },
    { word: 'EARTHQUAKE', clue: 'Ground shaking event' },
    { word: 'AVALANCHE', clue: 'Snow slide of doom' },
    { word: 'TORNADO', clue: 'Spinning wind funnel' },
    { word: 'HURRICANE', clue: 'Big spinning storm' },
    { word: 'MONSOON', clue: 'Seasonal rain season' },
    { word: 'CLIMATE', clue: 'Long-term weather pattern' },
    { word: 'EROSION', clue: 'Slow wearing away' },
    { word: 'SEDIMENT', clue: 'Settled particles' },
    { word: 'MINERALS', clue: 'Earth\'s natural compounds' },
    { word: 'FOSSIL', clue: 'Ancient life imprint' },
    { word: 'MAGMA', clue: 'Underground hot rock' },
    { word: 'TERRAIN', clue: 'Land surface type' },
    { word: 'HEMISPHERE', clue: 'Half of Earth' },
    { word: 'MERIDIAN', clue: 'Longitude line, prime one' },
    { word: 'COMPASS', clue: 'Direction finder' },
    { word: 'ATLAS', clue: 'Book of maps' },
    { word: 'CARTOGRAPHY', clue: 'Map making art' },
  ],

  music: [
    { word: 'SYMPHONY', clue: 'Orchestra\'s big show' },
    { word: 'GUITAR', clue: 'Six-stringed strummer' },
    { word: 'PIANO', clue: 'Black and white keys' },
    { word: 'VIOLIN', clue: 'Bow meets strings, elegant' },
    { word: 'DRUMS', clue: 'Hit things rhythmically' },
    { word: 'TRUMPET', clue: 'Brass horn, jazzy' },
    { word: 'SAXOPHONE', clue: 'Smooth jazz brass' },
    { word: 'FLUTE', clue: 'Blow across hole music' },
    { word: 'CLARINET', clue: 'Woodwind with reed' },
    { word: 'CELLO', clue: 'Big violin, sits between legs' },
    { word: 'HARMONICA', clue: 'Pocket piano, blow and suck' },
    { word: 'ACCORDION', clue: 'Squeezebox music maker' },
    { word: 'TAMBOURINE', clue: 'Shake and hit it' },
    { word: 'XYLOPHONE', clue: 'Hit wooden bars' },
    { word: 'RHYTHM', clue: 'Music\'s heartbeat' },
    { word: 'MELODY', clue: 'Tune you hum' },
    { word: 'HARMONY', clue: 'Notes that agree' },
    { word: 'TEMPO', clue: 'Speed of music' },
    { word: 'CHORUS', clue: 'Repeated catchy part' },
    { word: 'VERSE', clue: 'Song\'s story section' },
    { word: 'BRIDGE', clue: 'Song\'s connecting section' },
    { word: 'CRESCENDO', clue: 'Getting louder gradually' },
    { word: 'STACCATO', clue: 'Short, detached notes' },
    { word: 'LEGATO', clue: 'Smooth, connected notes' },
    { word: 'OCTAVE', clue: 'Eight notes apart' },
    { word: 'CHORD', clue: 'Multiple notes together' },
    { word: 'SCALE', clue: 'Do re mi fa so la ti' },
    { word: 'TREBLE', clue: 'High pitch clef' },
    { word: 'BASS', clue: 'Low pitch clef or fish' },
    { word: 'OPERA', clue: 'Singing drama, very dramatic' },
    { word: 'JAZZ', clue: 'Improvised American music' },
    { word: 'BLUES', clue: 'Sad but good music' },
    { word: 'ROCK', clue: 'Electric guitar music genre' },
    { word: 'CLASSICAL', clue: 'Mozart\'s genre' },
    { word: 'COUNTRY', clue: 'Twangy American music' },
    { word: 'REGGAE', clue: 'Jamaican rhythm music' },
    { word: 'HIPHOP', clue: 'Rap and beats' },
    { word: 'ELECTRONIC', clue: 'Computer-made beats' },
    { word: 'CONDUCTOR', clue: 'Orchestra\'s waver' },
    { word: 'COMPOSER', clue: 'Music writer' },
  ],

  sports: [
    { word: 'BASKETBALL', clue: 'Dribble and dunk game' },
    { word: 'FOOTBALL', clue: 'Touchdown game or soccer' },
    { word: 'BASEBALL', clue: 'Bat, ball, diamond' },
    { word: 'TENNIS', clue: 'Love means nothing here' },
    { word: 'GOLF', clue: 'Hit ball into hole slowly' },
    { word: 'SWIMMING', clue: 'Racing through water' },
    { word: 'CYCLING', clue: 'Pedal-powered racing' },
    { word: 'MARATHON', clue: '26.2 miles of running' },
    { word: 'VOLLEYBALL', clue: 'Net game, don\'t let it drop' },
    { word: 'HOCKEY', clue: 'Ice, puck, fights' },
    { word: 'CRICKET', clue: 'British bat sport, very long' },
    { word: 'RUGBY', clue: 'Football without pads' },
    { word: 'BOXING', clue: 'Punch but sportingly' },
    { word: 'WRESTLING', clue: 'Grappling competition' },
    { word: 'GYMNASTICS', clue: 'Flipping and balancing' },
    { word: 'ARCHERY', clue: 'Bow and arrow sport' },
    { word: 'FENCING', clue: 'Sword fighting sport' },
    { word: 'SKIING', clue: 'Sliding down snowy slopes' },
    { word: 'SURFING', clue: 'Riding ocean waves' },
    { word: 'SKATEBOARDING', clue: 'Tricks on four wheels' },
    { word: 'CLIMBING', clue: 'Scaling vertical surfaces' },
    { word: 'DIVING', clue: 'Jumping into water gracefully' },
    { word: 'ROWING', clue: 'Oar-powered boat racing' },
    { word: 'SAILING', clue: 'Wind-powered boat racing' },
    { word: 'TRIATHLON', clue: 'Swim, bike, run combo' },
    { word: 'DECATHLON', clue: 'Ten events, one athlete' },
    { word: 'JAVELIN', clue: 'Throwing a spear far' },
    { word: 'DISCUS', clue: 'Throwing a heavy disc' },
    { word: 'SHOTPUT', clue: 'Throwing heavy ball' },
    { word: 'HURDLES', clue: 'Running and jumping barriers' },
    { word: 'RELAY', clue: 'Team running with baton' },
    { word: 'SPRINTING', clue: 'Running very fast, briefly' },
    { word: 'LACROSSE', clue: 'Stick with net, catch ball' },
    { word: 'BADMINTON', clue: 'Shuttlecock sport' },
    { word: 'SQUASH', clue: 'Racket sport in box' },
    { word: 'POLO', clue: 'Horse-riding ball game' },
    { word: 'KARATE', clue: 'Japanese martial art' },
    { word: 'JUDO', clue: 'Throwing martial art' },
    { word: 'TAEKWONDO', clue: 'Korean kicking art' },
    { word: 'SNOWBOARDING', clue: 'One board, snowy slopes' },
  ],

  arts: [
    { word: 'PAINTING', clue: 'Brush meets canvas' },
    { word: 'SCULPTURE', clue: '3D art form' },
    { word: 'PHOTOGRAPHY', clue: 'Capturing light moments' },
    { word: 'CINEMA', clue: 'Moving picture art' },
    { word: 'THEATER', clue: 'Live performance art' },
    { word: 'BALLET', clue: 'Dancing on tippy toes' },
    { word: 'POETRY', clue: 'Words arranged beautifully' },
    { word: 'LITERATURE', clue: 'Written works of art' },
    { word: 'ARCHITECTURE', clue: 'Building as art' },
    { word: 'CERAMICS', clue: 'Clay art, fired' },
    { word: 'MOSAIC', clue: 'Picture from pieces' },
    { word: 'TAPESTRY', clue: 'Woven wall art' },
    { word: 'ORIGAMI', clue: 'Japanese paper folding' },
    { word: 'CALLIGRAPHY', clue: 'Beautiful handwriting art' },
    { word: 'GRAFFITI', clue: 'Street spray paint art' },
    { word: 'ABSTRACT', clue: 'Art without clear subject' },
    { word: 'REALISM', clue: 'Art copying reality' },
    { word: 'SURREALISM', clue: 'Dreamlike weird art' },
    { word: 'IMPRESSIONISM', clue: 'Monet\'s light-capturing style' },
    { word: 'CUBISM', clue: 'Picasso\'s geometric style' },
    { word: 'RENAISSANCE', clue: 'Art rebirth period' },
    { word: 'BAROQUE', clue: 'Dramatic ornate style' },
    { word: 'CONTEMPORARY', clue: 'Art of now' },
    { word: 'PORTRAIT', clue: 'Face painting or photo' },
    { word: 'LANDSCAPE', clue: 'Scenery artwork' },
    { word: 'STILLLIFE', clue: 'Painting of objects' },
    { word: 'WATERCOLOR', clue: 'Paint with water medium' },
    { word: 'ACRYLIC', clue: 'Fast-drying paint type' },
    { word: 'CHARCOAL', clue: 'Black drawing stick' },
    { word: 'PASTEL', clue: 'Soft colored chalk' },
    { word: 'CANVAS', clue: 'Painter\'s fabric surface' },
    { word: 'EASEL', clue: 'Holds canvas upright' },
    { word: 'PALETTE', clue: 'Paint mixing board' },
    { word: 'GALLERY', clue: 'Art display space' },
    { word: 'MUSEUM', clue: 'Art storage and display' },
    { word: 'EXHIBITION', clue: 'Art show event' },
    { word: 'MASTERPIECE', clue: 'Artist\'s best work' },
    { word: 'FRESCO', clue: 'Painting on wet plaster' },
    { word: 'ETCHING', clue: 'Acid-carved print art' },
    { word: 'COLLAGE', clue: 'Art from glued pieces' },
  ],

  nature: [
    { word: 'FOREST', clue: 'Tree community' },
    { word: 'MEADOW', clue: 'Grassy open field' },
    { word: 'STREAM', clue: 'Small flowing water' },
    { word: 'LAKE', clue: 'Contained water body' },
    { word: 'POND', clue: 'Small lake' },
    { word: 'RIVER', clue: 'Flowing to the sea' },
    { word: 'VALLEY', clue: 'Low land between hills' },
    { word: 'HILL', clue: 'Small mountain' },
    { word: 'CLIFF', clue: 'Vertical rock face' },
    { word: 'CAVE', clue: 'Hole in rock' },
    { word: 'ISLAND', clue: 'Land surrounded by water' },
    { word: 'BEACH', clue: 'Sandy shore' },
    { word: 'DUNE', clue: 'Sand hill' },
    { word: 'MARSH', clue: 'Wet grassy land' },
    { word: 'SWAMP', clue: 'Wet forest land' },
    { word: 'JUNGLE', clue: 'Dense tropical forest' },
    { word: 'PRAIRIE', clue: 'North American grassland' },
    { word: 'OASIS', clue: 'Desert water spot' },
    { word: 'SPRING', clue: 'Water source or season' },
    { word: 'GEYSER', clue: 'Hot water shooter' },
    { word: 'RAINBOW', clue: 'Colorful sky arc' },
    { word: 'SUNRISE', clue: 'Day\'s beginning light' },
    { word: 'SUNSET', clue: 'Day\'s ending colors' },
    { word: 'MOONLIGHT', clue: 'Night\'s borrowed glow' },
    { word: 'STARLIGHT', clue: 'Distant sun\'s twinkle' },
    { word: 'THUNDER', clue: 'Storm\'s loud voice' },
    { word: 'LIGHTNING', clue: 'Sky electricity' },
    { word: 'SNOWFLAKE', clue: 'Frozen unique crystal' },
    { word: 'RAINDROP', clue: 'Water from cloud' },
    { word: 'DEWDROP', clue: 'Morning moisture' },
    { word: 'FROST', clue: 'Icy morning coating' },
    { word: 'FOG', clue: 'Ground-level cloud' },
    { word: 'MIST', clue: 'Light fog' },
    { word: 'BREEZE', clue: 'Gentle wind' },
    { word: 'GALE', clue: 'Strong wind' },
    { word: 'STORM', clue: 'Violent weather' },
    { word: 'DROUGHT', clue: 'No rain period' },
    { word: 'FLOOD', clue: 'Too much water' },
    { word: 'TIDE', clue: 'Ocean\'s daily rhythm' },
    { word: 'WAVE', clue: 'Ocean\'s motion' },
  ],

  professions: [
    { word: 'DOCTOR', clue: 'Prescribes and heals' },
    { word: 'NURSE', clue: 'Doctor\'s right hand' },
    { word: 'TEACHER', clue: 'Shapes young minds' },
    { word: 'ENGINEER', clue: 'Builds and designs' },
    { word: 'ARCHITECT', clue: 'Designs buildings' },
    { word: 'LAWYER', clue: 'Argues in court' },
    { word: 'JUDGE', clue: 'Court decision maker' },
    { word: 'ACCOUNTANT', clue: 'Number cruncher' },
    { word: 'CHEF', clue: 'Professional cook' },
    { word: 'PILOT', clue: 'Flies the plane' },
    { word: 'ASTRONAUT', clue: 'Space traveler' },
    { word: 'SCIENTIST', clue: 'Studies the unknown' },
    { word: 'ARTIST', clue: 'Creates visual works' },
    { word: 'WRITER', clue: 'Word crafter' },
    { word: 'JOURNALIST', clue: 'Reports the news' },
    { word: 'PHOTOGRAPHER', clue: 'Captures moments' },
    { word: 'MUSICIAN', clue: 'Makes music' },
    { word: 'ACTOR', clue: 'Pretends professionally' },
    { word: 'DIRECTOR', clue: 'Leads film production' },
    { word: 'DESIGNER', clue: 'Creates visual solutions' },
    { word: 'PROGRAMMER', clue: 'Writes code' },
    { word: 'VETERINARIAN', clue: 'Animal doctor' },
    { word: 'DENTIST', clue: 'Tooth specialist' },
    { word: 'PHARMACIST', clue: 'Medicine dispenser' },
    { word: 'ELECTRICIAN', clue: 'Wires expert' },
    { word: 'PLUMBER', clue: 'Pipe fixer' },
    { word: 'MECHANIC', clue: 'Fixes machines' },
    { word: 'CARPENTER', clue: 'Works with wood' },
    { word: 'FIREFIGHTER', clue: 'Battles blazes' },
    { word: 'PARAMEDIC', clue: 'Emergency responder' },
    { word: 'LIBRARIAN', clue: 'Book organizer' },
    { word: 'THERAPIST', clue: 'Mental health helper' },
    { word: 'CONSULTANT', clue: 'Expert advisor' },
    { word: 'MANAGER', clue: 'Team leader' },
    { word: 'EXECUTIVE', clue: 'Top business leader' },
    { word: 'ENTREPRENEUR', clue: 'Business starter' },
    { word: 'RESEARCHER', clue: 'Seeks knowledge' },
    { word: 'PROFESSOR', clue: 'University teacher' },
    { word: 'TRANSLATOR', clue: 'Language converter' },
    { word: 'DIPLOMAT', clue: 'International relations expert' },
  ],
};

// Multilingual words (with English clues for accessibility)
const MULTILINGUAL = {
  spanish: [
    { word: 'AMOR', clue: 'Spanish love' },
    { word: 'VIDA', clue: 'Spanish life' },
    { word: 'SOL', clue: 'Spanish sun' },
    { word: 'LUNA', clue: 'Spanish moon' },
    { word: 'AGUA', clue: 'Spanish water' },
    { word: 'FUEGO', clue: 'Spanish fire' },
    { word: 'TIERRA', clue: 'Spanish earth' },
    { word: 'CIELO', clue: 'Spanish sky/heaven' },
    { word: 'NOCHE', clue: 'Spanish night' },
    { word: 'CASA', clue: 'Spanish house' },
    { word: 'TIEMPO', clue: 'Spanish time/weather' },
    { word: 'MUNDO', clue: 'Spanish world' },
    { word: 'CORAZON', clue: 'Spanish heart' },
    { word: 'FELIZ', clue: 'Spanish happy' },
    { word: 'GRANDE', clue: 'Spanish big' },
    { word: 'PEQUENO', clue: 'Spanish small' },
    { word: 'LIBRO', clue: 'Spanish book' },
    { word: 'AMIGO', clue: 'Spanish friend' },
    { word: 'FAMILIA', clue: 'Spanish family' },
    { word: 'TRABAJO', clue: 'Spanish work' },
    { word: 'CIUDAD', clue: 'Spanish city' },
    { word: 'PLAYA', clue: 'Spanish beach' },
    { word: 'FIESTA', clue: 'Spanish party' },
    { word: 'COMIDA', clue: 'Spanish food' },
    { word: 'MUSICA', clue: 'Spanish music' },
    { word: 'DULCE', clue: 'Spanish sweet' },
    { word: 'VERDE', clue: 'Spanish green' },
    { word: 'AZUL', clue: 'Spanish blue' },
    { word: 'ROJO', clue: 'Spanish red' },
    { word: 'BLANCO', clue: 'Spanish white' },
    { word: 'NEGRO', clue: 'Spanish black' },
    { word: 'PRIMAVERA', clue: 'Spanish spring' },
    { word: 'VERANO', clue: 'Spanish summer' },
    { word: 'OTONO', clue: 'Spanish autumn' },
    { word: 'INVIERNO', clue: 'Spanish winter' },
    { word: 'GRACIAS', clue: 'Spanish thanks' },
    { word: 'HOLA', clue: 'Spanish hello' },
    { word: 'ADIOS', clue: 'Spanish goodbye' },
    { word: 'BUENO', clue: 'Spanish good' },
    { word: 'NUEVO', clue: 'Spanish new' },
  ],

  french: [
    { word: 'AMOUR', clue: 'French love' },
    { word: 'JOUR', clue: 'French day' },
    { word: 'NUIT', clue: 'French night' },
    { word: 'CIEL', clue: 'French sky' },
    { word: 'SOLEIL', clue: 'French sun' },
    { word: 'LUNE', clue: 'French moon' },
    { word: 'ETOILE', clue: 'French star' },
    { word: 'FLEUR', clue: 'French flower' },
    { word: 'JARDIN', clue: 'French garden' },
    { word: 'MAISON', clue: 'French house' },
    { word: 'FROMAGE', clue: 'French cheese' },
    { word: 'PAIN', clue: 'French bread' },
    { word: 'CAFE', clue: 'French coffee' },
    { word: 'ROUGE', clue: 'French red' },
    { word: 'BLEU', clue: 'French blue' },
    { word: 'VERT', clue: 'French green' },
    { word: 'BLANC', clue: 'French white' },
    { word: 'NOIR', clue: 'French black' },
    { word: 'BEAU', clue: 'French beautiful (m)' },
    { word: 'BELLE', clue: 'French beautiful (f)' },
    { word: 'GRAND', clue: 'French big/tall' },
    { word: 'PETIT', clue: 'French small' },
    { word: 'BONJOUR', clue: 'French good day' },
    { word: 'MERCI', clue: 'French thanks' },
    { word: 'MONDE', clue: 'French world' },
    { word: 'LIVRE', clue: 'French book' },
    { word: 'MUSIQUE', clue: 'French music' },
    { word: 'CHANSON', clue: 'French song' },
    { word: 'DANSE', clue: 'French dance' },
    { word: 'VOYAGE', clue: 'French journey' },
    { word: 'PLAGE', clue: 'French beach' },
    { word: 'MONTAGNE', clue: 'French mountain' },
    { word: 'RIVIERE', clue: 'French river' },
    { word: 'CHATEAU', clue: 'French castle' },
    { word: 'HISTOIRE', clue: 'French story/history' },
    { word: 'TEMPS', clue: 'French time/weather' },
    { word: 'PRINTEMPS', clue: 'French spring' },
    { word: 'AUTOMNE', clue: 'French autumn' },
    { word: 'HIVER', clue: 'French winter' },
    { word: 'CUISINE', clue: 'French kitchen/cooking' },
  ],

  german: [
    { word: 'LIEBE', clue: 'German love' },
    { word: 'LEBEN', clue: 'German life' },
    { word: 'WELT', clue: 'German world' },
    { word: 'ZEIT', clue: 'German time' },
    { word: 'HAUS', clue: 'German house' },
    { word: 'STADT', clue: 'German city' },
    { word: 'LAND', clue: 'German country/land' },
    { word: 'WASSER', clue: 'German water' },
    { word: 'FEUER', clue: 'German fire' },
    { word: 'HIMMEL', clue: 'German sky/heaven' },
    { word: 'SONNE', clue: 'German sun' },
    { word: 'MOND', clue: 'German moon' },
    { word: 'STERN', clue: 'German star' },
    { word: 'BAUM', clue: 'German tree' },
    { word: 'BLUME', clue: 'German flower' },
    { word: 'BERG', clue: 'German mountain' },
    { word: 'FLUSS', clue: 'German river' },
    { word: 'WALD', clue: 'German forest' },
    { word: 'STRASSE', clue: 'German street' },
    { word: 'BUCH', clue: 'German book' },
    { word: 'MUSIK', clue: 'German music' },
    { word: 'KUNST', clue: 'German art' },
    { word: 'FREUND', clue: 'German friend' },
    { word: 'FAMILIE', clue: 'German family' },
    { word: 'ARBEIT', clue: 'German work' },
    { word: 'SCHULE', clue: 'German school' },
    { word: 'GARTEN', clue: 'German garden' },
    { word: 'KAFFEE', clue: 'German coffee' },
    { word: 'KUCHEN', clue: 'German cake' },
    { word: 'BROT', clue: 'German bread' },
    { word: 'WEIN', clue: 'German wine' },
    { word: 'BIER', clue: 'German beer' },
    { word: 'DANKE', clue: 'German thanks' },
    { word: 'BITTE', clue: 'German please' },
    { word: 'GUTEN', clue: 'German good' },
    { word: 'MORGEN', clue: 'German morning/tomorrow' },
    { word: 'ABEND', clue: 'German evening' },
    { word: 'NACHT', clue: 'German night' },
    { word: 'SCHNELL', clue: 'German fast' },
    { word: 'GROSS', clue: 'German big' },
  ],

  italian: [
    { word: 'AMORE', clue: 'Italian love' },
    { word: 'VITA', clue: 'Italian life' },
    { word: 'SOLE', clue: 'Italian sun' },
    { word: 'LUNA', clue: 'Italian moon' },
    { word: 'STELLA', clue: 'Italian star' },
    { word: 'CIELO', clue: 'Italian sky' },
    { word: 'MARE', clue: 'Italian sea' },
    { word: 'ACQUA', clue: 'Italian water' },
    { word: 'FUOCO', clue: 'Italian fire' },
    { word: 'TERRA', clue: 'Italian earth' },
    { word: 'CASA', clue: 'Italian house' },
    { word: 'CUORE', clue: 'Italian heart' },
    { word: 'FIORE', clue: 'Italian flower' },
    { word: 'ALBERO', clue: 'Italian tree' },
    { word: 'GIARDINO', clue: 'Italian garden' },
    { word: 'MONTAGNA', clue: 'Italian mountain' },
    { word: 'FIUME', clue: 'Italian river' },
    { word: 'PIAZZA', clue: 'Italian square/plaza' },
    { word: 'STRADA', clue: 'Italian street' },
    { word: 'LIBRO', clue: 'Italian book' },
    { word: 'MUSICA', clue: 'Italian music' },
    { word: 'ARTE', clue: 'Italian art' },
    { word: 'BELLEZZA', clue: 'Italian beauty' },
    { word: 'DOLCE', clue: 'Italian sweet' },
    { word: 'FAMIGLIA', clue: 'Italian family' },
    { word: 'AMICO', clue: 'Italian friend' },
    { word: 'BAMBINO', clue: 'Italian child' },
    { word: 'DONNA', clue: 'Italian woman' },
    { word: 'UOMO', clue: 'Italian man' },
    { word: 'GRAZIE', clue: 'Italian thanks' },
    { word: 'PREGO', clue: 'Italian you\'re welcome' },
    { word: 'CIAO', clue: 'Italian hi/bye' },
    { word: 'BUONO', clue: 'Italian good' },
    { word: 'BELLO', clue: 'Italian beautiful' },
    { word: 'GRANDE', clue: 'Italian big' },
    { word: 'PICCOLO', clue: 'Italian small' },
    { word: 'ROSSO', clue: 'Italian red' },
    { word: 'VERDE', clue: 'Italian green' },
    { word: 'BIANCO', clue: 'Italian white' },
    { word: 'NERO', clue: 'Italian black' },
  ],

  japanese: [
    { word: 'SAKURA', clue: 'Japanese cherry blossom' },
    { word: 'SAMURAI', clue: 'Japanese warrior' },
    { word: 'NINJA', clue: 'Japanese stealth warrior' },
    { word: 'SUSHI', clue: 'Japanese rice dish' },
    { word: 'SAKE', clue: 'Japanese rice wine' },
    { word: 'RAMEN', clue: 'Japanese noodle soup' },
    { word: 'ORIGAMI', clue: 'Japanese paper folding' },
    { word: 'KARATE', clue: 'Japanese martial art' },
    { word: 'JUDO', clue: 'Japanese grappling art' },
    { word: 'SUMO', clue: 'Japanese wrestling' },
    { word: 'KIMONO', clue: 'Japanese robe' },
    { word: 'GEISHA', clue: 'Japanese entertainer' },
    { word: 'SHOGUN', clue: 'Japanese military ruler' },
    { word: 'TSUNAMI', clue: 'Japanese harbor wave' },
    { word: 'TOFU', clue: 'Japanese soy curd' },
    { word: 'WASABI', clue: 'Japanese green spice' },
    { word: 'KARAOKE', clue: 'Japanese empty orchestra' },
    { word: 'MANGA', clue: 'Japanese comics' },
    { word: 'ANIME', clue: 'Japanese animation' },
    { word: 'SENSEI', clue: 'Japanese teacher' },
    { word: 'DOJO', clue: 'Japanese training hall' },
    { word: 'TATAMI', clue: 'Japanese floor mat' },
    { word: 'FUTON', clue: 'Japanese bedding' },
    { word: 'IKEBANA', clue: 'Japanese flower arranging' },
    { word: 'BONSAI', clue: 'Japanese miniature tree' },
    { word: 'HAIKU', clue: 'Japanese short poem' },
    { word: 'KABUKI', clue: 'Japanese theater form' },
    { word: 'TEMPURA', clue: 'Japanese fried food' },
    { word: 'TERIYAKI', clue: 'Japanese glaze style' },
    { word: 'MATCHA', clue: 'Japanese green tea' },
  ],

  portuguese: [
    { word: 'AMOR', clue: 'Portuguese love' },
    { word: 'VIDA', clue: 'Portuguese life' },
    { word: 'SOL', clue: 'Portuguese sun' },
    { word: 'LUA', clue: 'Portuguese moon' },
    { word: 'MAR', clue: 'Portuguese sea' },
    { word: 'PRAIA', clue: 'Portuguese beach' },
    { word: 'CASA', clue: 'Portuguese house' },
    { word: 'CIDADE', clue: 'Portuguese city' },
    { word: 'MUNDO', clue: 'Portuguese world' },
    { word: 'TEMPO', clue: 'Portuguese time/weather' },
    { word: 'FELIZ', clue: 'Portuguese happy' },
    { word: 'GRANDE', clue: 'Portuguese big' },
    { word: 'PEQUENO', clue: 'Portuguese small' },
    { word: 'BONITO', clue: 'Portuguese beautiful' },
    { word: 'SAUDADE', clue: 'Portuguese longing (untranslatable)' },
    { word: 'OBRIGADO', clue: 'Portuguese thanks (m)' },
    { word: 'FAMILIA', clue: 'Portuguese family' },
    { word: 'AMIGO', clue: 'Portuguese friend' },
    { word: 'MUSICA', clue: 'Portuguese music' },
    { word: 'VERDE', clue: 'Portuguese green' },
  ],
};

// Additional common English words
const COMMON_ENGLISH: Array<{ word: string; clue: string }> = [
  { word: 'ADVENTURE', clue: 'Exciting journey' },
  { word: 'BEAUTIFUL', clue: 'Pleasing to see' },
  { word: 'CELEBRATE', clue: 'Party time' },
  { word: 'DELICIOUS', clue: 'Tastes amazing' },
  { word: 'EXCELLENT', clue: 'Top quality' },
  { word: 'FANTASTIC', clue: 'Wonderfully good' },
  { word: 'GORGEOUS', clue: 'Stunningly pretty' },
  { word: 'HAPPINESS', clue: 'State of joy' },
  { word: 'INCREDIBLE', clue: 'Hard to believe' },
  { word: 'JOYFUL', clue: 'Full of happiness' },
  { word: 'KNOWLEDGE', clue: 'What you learn' },
  { word: 'LEGENDARY', clue: 'Famous through stories' },
  { word: 'MAGNIFICENT', clue: 'Impressively grand' },
  { word: 'NATURAL', clue: 'From nature' },
  { word: 'OUTSTANDING', clue: 'Exceptionally good' },
  { word: 'PEACEFUL', clue: 'Calm and quiet' },
  { word: 'QUESTION', clue: 'What you ask' },
  { word: 'REMARKABLE', clue: 'Worth noting' },
  { word: 'SPECTACULAR', clue: 'Dramatically impressive' },
  { word: 'TREASURE', clue: 'Valuable find' },
  { word: 'UMBRELLA', clue: 'Rain blocker' },
  { word: 'VACATION', clue: 'Time off travel' },
  { word: 'WONDERFUL', clue: 'Inspiring wonder' },
  { word: 'YESTERDAY', clue: 'Day before today' },
  { word: 'AMAZING', clue: 'Causes amazement' },
  { word: 'BRILLIANT', clue: 'Very bright or clever' },
  { word: 'CREATIVE', clue: 'Makes new things' },
  { word: 'DISCOVERY', clue: 'Finding something new' },
  { word: 'ENERGY', clue: 'Power to do things' },
  { word: 'FREEDOM', clue: 'State of being free' },
  { word: 'GENEROUS', clue: 'Gives freely' },
  { word: 'HARMONY', clue: 'Pleasant agreement' },
  { word: 'IMAGINE', clue: 'Picture in your mind' },
  { word: 'JOURNEY', clue: 'Trip from A to B' },
  { word: 'KINDNESS', clue: 'Being nice' },
  { word: 'LAUGHTER', clue: 'Sound of joy' },
  { word: 'MYSTERY', clue: 'Unsolved puzzle' },
  { word: 'NOVEMBER', clue: 'Eleventh month' },
  { word: 'OCTOBER', clue: 'Tenth month' },
  { word: 'PARADISE', clue: 'Perfect place' },
  { word: 'QUALITY', clue: 'How good something is' },
  { word: 'RAINBOW', clue: 'Colorful arc' },
  { word: 'SUNSHINE', clue: 'Light from the sun' },
  { word: 'TOGETHER', clue: 'With each other' },
  { word: 'UNIVERSE', clue: 'Everything that exists' },
  { word: 'VICTORY', clue: 'Winning' },
  { word: 'WISDOM', clue: 'Deep knowledge' },
  { word: 'EXCITED', clue: 'Very eager' },
  { word: 'YEARNING', clue: 'Strong desire' },
  { word: 'ZEALOUS', clue: 'Very enthusiastic' },
  { word: 'ABSOLUTE', clue: 'Complete, total' },
  { word: 'BALANCE', clue: 'Equal distribution' },
  { word: 'CAPTAIN', clue: 'Ship leader' },
  { word: 'DIAMOND', clue: 'Hardest gemstone' },
  { word: 'ELEPHANT', clue: 'Largest land animal' },
  { word: 'FAMOUS', clue: 'Well known' },
  { word: 'GALAXY', clue: 'Star system' },
  { word: 'HORIZON', clue: 'Where sky meets land' },
  { word: 'INSTANT', clue: 'Immediate moment' },
  { word: 'JUSTICE', clue: 'Fairness in law' },
  { word: 'KITCHEN', clue: 'Cooking room' },
  { word: 'LIBRARY', clue: 'Book repository' },
  { word: 'MONSTER', clue: 'Scary creature' },
  { word: 'NETWORK', clue: 'Connected system' },
  { word: 'OPINION', clue: 'Personal view' },
  { word: 'PERFECT', clue: 'Without flaws' },
  { word: 'QUARTER', clue: 'One fourth' },
  { word: 'RESPECT', clue: 'Admiration given' },
  { word: 'SILENCE', clue: 'Complete quiet' },
  { word: 'THUNDER', clue: 'Storm sound' },
  { word: 'UNUSUAL', clue: 'Not common' },
  { word: 'VILLAGE', clue: 'Small town' },
  { word: 'WEATHER', clue: 'Atmospheric conditions' },
  { word: 'EXAMPLE', clue: 'Sample instance' },
  { word: 'YOUNG', clue: 'Not old' },
  { word: 'ZEBRA', clue: 'Striped horse' },
  { word: 'ANCHOR', clue: 'Ship stopper' },
  { word: 'BROTHER', clue: 'Male sibling' },
  { word: 'CHANNEL', clue: 'Water passage or TV station' },
  { word: 'DOLPHIN', clue: 'Smart sea mammal' },
  { word: 'EVENING', clue: 'Late day time' },
  { word: 'FORTUNE', clue: 'Wealth or luck' },
  { word: 'GENERAL', clue: 'Army leader' },
  { word: 'HISTORY', clue: 'Past events' },
  { word: 'INNOCENT', clue: 'Not guilty' },
  { word: 'JEALOUS', clue: 'Envious feeling' },
  { word: 'KINGDOM', clue: 'Monarch\'s realm' },
  { word: 'LEOPARD', clue: 'Spotted big cat' },
  { word: 'MACHINE', clue: 'Mechanical device' },
  { word: 'NERVOUS', clue: 'Anxious feeling' },
  { word: 'OBSERVE', clue: 'Watch carefully' },
  { word: 'PATTERN', clue: 'Repeated design' },
  { word: 'QUANTUM', clue: 'Smallest unit' },
  { word: 'REFLECT', clue: 'Mirror back' },
  { word: 'SHADOW', clue: 'Dark silhouette' },
  { word: 'TORNADO', clue: 'Spinning wind' },
  { word: 'UNIFORM', clue: 'Standard outfit' },
  { word: 'VAMPIRE', clue: 'Blood-drinking creature' },
  { word: 'WHISPER', clue: 'Quiet talk' },
  { word: 'EXTREME', clue: 'Very intense' },
  { word: 'YELLOW', clue: 'Banana color' },
  { word: 'ZODIAC', clue: 'Star sign system' },
];

// Generate word database
export function generateWordDatabase(targetCount: number = 10000): Word[] {
  const words: Word[] = [];
  const usedWords = new Set<string>();

  // Helper to add words without duplicates
  const addWords = (
    wordList: Array<{ word: string; clue: string }>,
    language: string,
    topic: string
  ) => {
    for (const { word, clue } of wordList) {
      const normalized = word.toUpperCase().replace(/[^A-Z]/g, '');
      if (normalized.length >= 3 && !usedWords.has(normalized)) {
        usedWords.add(normalized);
        words.push({
          text: normalized,
          clue,
          language,
          topic,
        });
      }
    }
  };

  // Add topic words
  for (const [topic, wordList] of Object.entries(TOPICS)) {
    addWords(wordList, 'english', topic);
  }

  // Add multilingual words
  for (const [language, wordList] of Object.entries(MULTILINGUAL)) {
    addWords(wordList, language, 'language');
  }

  // Add common English words
  addWords(COMMON_ENGLISH, 'english', 'general');

  // Generate additional words algorithmically to reach target
  const prefixes = ['UN', 'RE', 'PRE', 'MIS', 'DIS', 'OVER', 'UNDER', 'OUT', 'SUPER', 'ANTI', 'AUTO', 'SEMI', 'INTER', 'MULTI', 'ULTRA', 'MEGA', 'MICRO', 'MINI', 'MACRO', 'NEO', 'POST', 'TRANS', 'SUB'];
  const suffixes = ['ING', 'TION', 'NESS', 'MENT', 'ABLE', 'IBLE', 'FUL', 'LESS', 'IOUS', 'EOUS', 'ICAL', 'ICAL', 'OLOGY', 'OGRAPHY', 'WARD', 'WISE', 'LIKE', 'SHIP', 'HOOD', 'DOM'];
  const roots = ['FORM', 'GRAPH', 'LOG', 'DICT', 'STRUCT', 'JECT', 'SPECT', 'PORT', 'TRACT', 'SCRIBE', 'CRED', 'VERT', 'VENE', 'FACT', 'FECT', 'PRESS', 'POSE', 'VOLVE', 'SIST', 'MIT', 'CEDE', 'GRESS', 'DUCE', 'RECT', 'TEND', 'SENS', 'PATH', 'PEND', 'MAND', 'CEPT'];

  // Generate compound words
  const baseWords = Array.from(usedWords);
  while (words.length < targetCount && baseWords.length > 0) {
    // Try prefix + base
    for (const prefix of prefixes) {
      if (words.length >= targetCount) break;
      for (const root of roots) {
        const word = prefix + root;
        if (word.length >= 4 && word.length <= 15 && !usedWords.has(word)) {
          usedWords.add(word);
          words.push({
            text: word,
            clue: `${prefix.toLowerCase()}- word with ${root.toLowerCase()}`,
            language: 'english',
            topic: 'compound',
          });
        }
      }
    }

    // Try base + suffix
    for (const suffix of suffixes) {
      if (words.length >= targetCount) break;
      for (const root of roots) {
        const word = root + suffix;
        if (word.length >= 4 && word.length <= 15 && !usedWords.has(word)) {
          usedWords.add(word);
          words.push({
            text: word,
            clue: `Word ending in -${suffix.toLowerCase()}`,
            language: 'english',
            topic: 'compound',
          });
        }
      }
    }

    // Generate more themed words
    const moreWords = generateThemedWords();
    for (const w of moreWords) {
      if (words.length >= targetCount) break;
      const normalized = w.word.toUpperCase();
      if (!usedWords.has(normalized) && normalized.length >= 3 && normalized.length <= 15) {
        usedWords.add(normalized);
        words.push({
          text: normalized,
          clue: w.clue,
          language: 'english',
          topic: w.topic,
        });
      }
    }

    break; // Prevent infinite loop
  }

  console.log(`Generated ${words.length} unique words`);
  return words;
}

// Generate additional themed words
function generateThemedWords(): Array<{ word: string; clue: string; topic: string }> {
  return [
    // Colors
    { word: 'CRIMSON', clue: 'Deep red color', topic: 'colors' },
    { word: 'SCARLET', clue: 'Bright red shade', topic: 'colors' },
    { word: 'MAGENTA', clue: 'Pinkish purple', topic: 'colors' },
    { word: 'CYAN', clue: 'Blue-green color', topic: 'colors' },
    { word: 'TEAL', clue: 'Blue-green shade', topic: 'colors' },
    { word: 'CORAL', clue: 'Pinkish orange', topic: 'colors' },
    { word: 'AMBER', clue: 'Golden yellow', topic: 'colors' },
    { word: 'INDIGO', clue: 'Deep blue-purple', topic: 'colors' },
    { word: 'VIOLET', clue: 'Purple flower color', topic: 'colors' },
    { word: 'MAROON', clue: 'Dark brownish red', topic: 'colors' },
    { word: 'NAVY', clue: 'Dark blue', topic: 'colors' },
    { word: 'OLIVE', clue: 'Yellowish green', topic: 'colors' },
    { word: 'TURQUOISE', clue: 'Blue-green gem color', topic: 'colors' },
    { word: 'LAVENDER', clue: 'Light purple', topic: 'colors' },
    { word: 'IVORY', clue: 'Creamy white', topic: 'colors' },
    { word: 'BEIGE', clue: 'Sandy tan', topic: 'colors' },
    { word: 'BRONZE', clue: 'Metal brown', topic: 'colors' },
    { word: 'SILVER', clue: 'Shiny grey metal', topic: 'colors' },
    { word: 'GOLDEN', clue: 'Like gold', topic: 'colors' },
    { word: 'PLATINUM', clue: 'Silvery white metal', topic: 'colors' },

    // Emotions
    { word: 'EUPHORIA', clue: 'Intense happiness', topic: 'emotions' },
    { word: 'SERENITY', clue: 'Calm peacefulness', topic: 'emotions' },
    { word: 'ANXIETY', clue: 'Worry feeling', topic: 'emotions' },
    { word: 'NOSTALGIA', clue: 'Longing for past', topic: 'emotions' },
    { word: 'EMPATHY', clue: 'Understanding others feelings', topic: 'emotions' },
    { word: 'GRATITUDE', clue: 'Thankful feeling', topic: 'emotions' },
    { word: 'COURAGE', clue: 'Bravery', topic: 'emotions' },
    { word: 'COMPASSION', clue: 'Caring for others', topic: 'emotions' },
    { word: 'CURIOSITY', clue: 'Desire to know', topic: 'emotions' },
    { word: 'ENTHUSIASM', clue: 'Eager excitement', topic: 'emotions' },

    // Space
    { word: 'COSMOS', clue: 'The universe', topic: 'space' },
    { word: 'STELLAR', clue: 'Of the stars', topic: 'space' },
    { word: 'LUNAR', clue: 'Of the moon', topic: 'space' },
    { word: 'SOLAR', clue: 'Of the sun', topic: 'space' },
    { word: 'ORBITAL', clue: 'Going around', topic: 'space' },
    { word: 'GALACTIC', clue: 'Of galaxies', topic: 'space' },
    { word: 'CELESTIAL', clue: 'Of the sky', topic: 'space' },
    { word: 'MARTIAN', clue: 'From Mars', topic: 'space' },
    { word: 'VENUS', clue: 'Second planet', topic: 'space' },
    { word: 'MERCURY', clue: 'First planet', topic: 'space' },
    { word: 'SATURN', clue: 'Ringed planet', topic: 'space' },
    { word: 'URANUS', clue: 'Tilted planet', topic: 'space' },
    { word: 'NEPTUNE', clue: 'Blue distant planet', topic: 'space' },
    { word: 'PLUTO', clue: 'Dwarf planet', topic: 'space' },
    { word: 'METEOR', clue: 'Shooting star', topic: 'space' },
    { word: 'CRATER', clue: 'Impact hole', topic: 'space' },
    { word: 'ORBIT', clue: 'Circular path', topic: 'space' },
    { word: 'GRAVITY', clue: 'What pulls you down', topic: 'space' },
    { word: 'ROCKET', clue: 'Space vehicle', topic: 'space' },
    { word: 'ALIEN', clue: 'Extraterrestrial', topic: 'space' },

    // More animals
    { word: 'PHOENIX', clue: 'Mythical fire bird', topic: 'mythology' },
    { word: 'DRAGON', clue: 'Fire-breathing legend', topic: 'mythology' },
    { word: 'UNICORN', clue: 'Horned horse myth', topic: 'mythology' },
    { word: 'GRIFFIN', clue: 'Eagle-lion hybrid', topic: 'mythology' },
    { word: 'PEGASUS', clue: 'Winged horse', topic: 'mythology' },
    { word: 'SPHINX', clue: 'Riddle creature', topic: 'mythology' },
    { word: 'KRAKEN', clue: 'Sea monster', topic: 'mythology' },
    { word: 'MERMAID', clue: 'Fish-human hybrid', topic: 'mythology' },
    { word: 'CENTAUR', clue: 'Horse-human hybrid', topic: 'mythology' },
    { word: 'MINOTAUR', clue: 'Bull-headed creature', topic: 'mythology' },

    // Architecture
    { word: 'CATHEDRAL', clue: 'Grand church', topic: 'architecture' },
    { word: 'PYRAMID', clue: 'Egyptian tomb shape', topic: 'architecture' },
    { word: 'TEMPLE', clue: 'Sacred building', topic: 'architecture' },
    { word: 'PALACE', clue: 'Royal residence', topic: 'architecture' },
    { word: 'FORTRESS', clue: 'Defensive structure', topic: 'architecture' },
    { word: 'TOWER', clue: 'Tall structure', topic: 'architecture' },
    { word: 'BRIDGE', clue: 'Gap crosser', topic: 'architecture' },
    { word: 'MONUMENT', clue: 'Memorial structure', topic: 'architecture' },
    { word: 'SKYSCRAPER', clue: 'Very tall building', topic: 'architecture' },
    { word: 'DOME', clue: 'Rounded roof', topic: 'architecture' },

    // Materials
    { word: 'MARBLE', clue: 'Fancy stone', topic: 'materials' },
    { word: 'GRANITE', clue: 'Hard stone', topic: 'materials' },
    { word: 'CRYSTAL', clue: 'Clear mineral', topic: 'materials' },
    { word: 'CERAMIC', clue: 'Fired clay', topic: 'materials' },
    { word: 'VELVET', clue: 'Soft fabric', topic: 'materials' },
    { word: 'SILK', clue: 'Smooth fabric', topic: 'materials' },
    { word: 'COTTON', clue: 'Plant fiber fabric', topic: 'materials' },
    { word: 'LEATHER', clue: 'Animal hide', topic: 'materials' },
    { word: 'BAMBOO', clue: 'Tall grass material', topic: 'materials' },
    { word: 'MAHOGANY', clue: 'Fine wood', topic: 'materials' },

    // Time
    { word: 'MOMENT', clue: 'Brief instant', topic: 'time' },
    { word: 'CENTURY', clue: '100 years', topic: 'time' },
    { word: 'DECADE', clue: '10 years', topic: 'time' },
    { word: 'MILLENNIUM', clue: '1000 years', topic: 'time' },
    { word: 'ETERNAL', clue: 'Forever lasting', topic: 'time' },
    { word: 'ANCIENT', clue: 'Very old', topic: 'time' },
    { word: 'MODERN', clue: 'Current times', topic: 'time' },
    { word: 'FUTURE', clue: 'What comes next', topic: 'time' },
    { word: 'MIDNIGHT', clue: '12 AM', topic: 'time' },
    { word: 'TWILIGHT', clue: 'Dusk time', topic: 'time' },

    // Additional words for variety
    { word: 'QUANTUM', clue: 'Physics of very small', topic: 'science' },
    { word: 'ENIGMA', clue: 'Puzzling mystery', topic: 'general' },
    { word: 'ZEPHYR', clue: 'Gentle breeze', topic: 'nature' },
    { word: 'ODYSSEY', clue: 'Long journey', topic: 'literature' },
    { word: 'LABYRINTH', clue: 'Complex maze', topic: 'mythology' },
    { word: 'SERENDIPITY', clue: 'Happy accident', topic: 'general' },
    { word: 'EPIPHANY', clue: 'Sudden realization', topic: 'general' },
    { word: 'CHARISMA', clue: 'Personal magnetism', topic: 'general' },
    { word: 'KALEIDOSCOPE', clue: 'Colorful viewer', topic: 'general' },
    { word: 'SYNCHRONIZE', clue: 'Match timing', topic: 'general' },
    { word: 'PHENOMENON', clue: 'Observable occurrence', topic: 'science' },
    { word: 'RENAISSANCE', clue: 'Cultural rebirth', topic: 'history' },
    { word: 'REVOLUTION', clue: 'Major change or rotation', topic: 'history' },
    { word: 'CIVILIZATION', clue: 'Advanced society', topic: 'history' },
    { word: 'DEMOCRACY', clue: 'People\'s rule', topic: 'politics' },
    { word: 'PHILOSOPHY', clue: 'Love of wisdom', topic: 'academics' },
    { word: 'PSYCHOLOGY', clue: 'Mind study', topic: 'academics' },
    { word: 'SOCIOLOGY', clue: 'Society study', topic: 'academics' },
    { word: 'ECONOMICS', clue: 'Money and trade study', topic: 'academics' },
    { word: 'MATHEMATICS', clue: 'Number science', topic: 'academics' },
  ];
}

// Export a pre-generated database for quick loading
export const WORD_DATABASE = generateWordDatabase(10000);
